version: '2'
services:
  php:
    container_name: apache2_php
    build: .
    volumes:
      - "./configs/php/php.ini:/usr/local/etc/php/php.ini"
      - "./configs/httpd/devops.site.conf:/etc/apache2/sites-available/000-default.conf"
      - "/var/www/utn-devops-app:/var/www/html"
    ports:
      - "8081:80" 
    depends_on:
      - db
  db:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_DATABASE=devops_app #crear√° una base de datos con ese nombre
      - MYSQL_ROOT_PASSWORD=root #clave de administrador del servidor MySQL
    ports:
      - "4400:3306"
    volumes:
      - /var/db/mysql:/var/lib/mysql
      - "./configs/mysql/script.sql:/tmp/script.sql"