version: '3.8'
services:
  php:
    container_name: apache2_php
    build: .
    volumes:
      - "./configs/php/php.ini:/usr/local/etc/php/php.ini"
      - "./configs/httpd/devops.site.conf:/etc/apache2/sites-available/000-default.conf"
      - "./configs/app/.env:/var/www/html/myapp/.env"
      - "./configs/app/config_app.sh:/tmp/config_app.sh"
      - "/var/www/utn-devops-app:/var/www/html"
    ports:
      - "8081:80"
    depends_on:
      - db_server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network
  db_server:
    image: mysql/mysql-server:8.0.23
    container_name: mysql
    environment:
      - MYSQL_DATABASE=devops_app #crear√° una base de datos con ese nombre
      - MYSQL_ROOT_PASSWORD=root #clave de administrador del servidor MySQL
      - MYSQL_ROOT_HOST=%
    ports:
      - "4400:3306"
    volumes:
      - db_data:/var/lib/mysql
      - "./configs/mysql/script.sql:/tmp/script.sql"
    networks:
      - app-network
volumes:
  db_data:
    driver: local
networks:
  app-network:
    driver: bridge
