version: '2'
services:
  php:
    container_name: apache2_php
    build: .
    volumes:
      - "/var/www/utn-devops-app:/var/www/html"
    ports:
      - "8081:80" 
    depends_on:
      - db_server
  db_server:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_DATABASE=devops_app #crear√° una base de datos con ese nombre
      - MYSQL_ROOT_PASSWORD=root #clave de administrador del servidor MySQL
    ports:
      - "4400:3306"
    volumes:
      - /var/db/mysql:/var/lib/mysql
      - "./configs/mysql/script.sql:/tmp/script.sql"
